/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myrestoran;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        Border global_panel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        jPanel4.setBorder(global_panel_border);
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimaze.setBorder(label_border);
        jLabel_close.setBorder(label_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_minimaze = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jButton_inputMenu = new javax.swing.JButton();
        jButton_transaksi = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_minimaze.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_minimaze.setText(" - ");
        jLabel_minimaze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimaze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimazeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimazeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimazeMouseExited(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_close.setText(" x ");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jButton_inputMenu.setBackground(new java.awt.Color(0, 84, 140));
        jButton_inputMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_inputMenu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_inputMenu.setText("Input Menu");
        jButton_inputMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_inputMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_inputMenuMouseExited(evt);
            }
        });
        jButton_inputMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_inputMenuActionPerformed(evt);
            }
        });

        jButton_transaksi.setBackground(new java.awt.Color(0, 84, 140));
        jButton_transaksi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        jButton_transaksi.setText("Transaksi");
        jButton_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_transaksiMouseExited(evt);
            }
        });
        jButton_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_transaksiActionPerformed(evt);
            }
        });

        jButton_logout.setBackground(new java.awt.Color(0, 84, 140));
        jButton_logout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_logout.setText("Logout");
        jButton_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_logoutMouseExited(evt);
            }
        });
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabel_minimaze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_inputMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_minimaze)
                    .addComponent(jLabel_close))
                .addGap(40, 40, 40)
                .addComponent(jButton_inputMenu)
                .addGap(18, 18, 18)
                .addComponent(jButton_transaksi)
                .addGap(18, 18, 18)
                .addComponent(jButton_logout)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimazeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimazeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimazeMouseClicked

    private void jLabel_minimazeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimazeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimaze.setForeground(Color.white);
        jLabel_minimaze.setBorder(label_border);
    }//GEN-LAST:event_jLabel_minimazeMouseEntered

    private void jLabel_minimazeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimazeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimaze.setBorder(label_border);
        jLabel_minimaze.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimazeMouseExited

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close.setForeground(Color.white);
        jLabel_close.setBorder(label_border);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jButton_inputMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_inputMenuActionPerformed
        FormInputMenu im = new FormInputMenu();
        im.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_inputMenuActionPerformed

    private void jButton_inputMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_inputMenuMouseEntered
         jButton_inputMenu.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_jButton_inputMenuMouseEntered

    private void jButton_inputMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_inputMenuMouseExited
        jButton_inputMenu.setBackground(new Color(0, 84, 104));
    }//GEN-LAST:event_jButton_inputMenuMouseExited

    private void jButton_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_transaksiMouseEntered
        jButton_transaksi.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_jButton_transaksiMouseEntered

    private void jButton_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_transaksiMouseExited
        jButton_transaksi.setBackground(new Color(0, 84, 104));
    }//GEN-LAST:event_jButton_transaksiMouseExited

    private void jButton_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_transaksiActionPerformed
        Transaksi tr = new Transaksi();
        tr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_transaksiActionPerformed

    private void jButton_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_logoutMouseEntered
        jButton_logout.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_jButton_logoutMouseEntered

    private void jButton_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_logoutMouseExited
        jButton_logout.setBackground(new Color(0, 84, 104));
    }//GEN-LAST:event_jButton_logoutMouseExited

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_inputMenu;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_transaksi;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_minimaze;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
